apiVersion: apps/v1
kind: Deployment
metadata:
  name: osqueryi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osqueryi
  template:
    metadata:
      name: osqueryi
      labels:
        app: osqueryi
    spec:
      containers:
      - name: cloud-data
        image: osquery-kubelet-skaffold
